@startuml
package "Activities" <<rectangle>>  {
    class WorkoutActivity{
        -Button BeginWorkoutButton
        -Button EndWorkoutButton
        -Button PauseWorkoutButton
        -Button MakeCommentButton

    }

    class WorkoutHistoryActivity{
        -TODO
    }
    class WorkoutSessionDetailsActivity{
        -TODO
    }
    class SettingsActivity{
        - SharedPreferenceHelper sharedPreferenceHelper
        - Button SaveSettingsButton
        - Button EditSettingsButton

    }
    interface NavBar
}

together {
    class ECGDataCollectionService{
        + ECG_STATUS startECGCapture()
        + ECG_STATUS makeTimestampedComment(String)
        + ECG_STATUS getStatus()
        + void connectBLE()
        + void stopECGCapture()
        - Override BLE_Callback()
        - List<short> waveformDataBuffer
        - ECGSession currentSession
        - ECG_STATUS currentStatus
    }

    class DataStorage{
        + List<ECGSession> getSessionList()
        + void saveWaveform(ECGSession, List<Short>)
        - List<SessionEntity> SessionList
    }



    class SendDoctorDataService{
        - SharedPreferenceHelper sharedPreferenceHelper
    }
}
package "Data Classes" <<rectangle>>{
    class SessionEntity{
        + int sId
        + Date mSessionStart
        + Date mSessionEnd
        + String mSessionComments
        + String mSessionDataFileName
    }
    class ECGSession{
        - Date startTime
        - Date stopTime
        - String timestampedComments
        + stopSession()
        + addComment(String)
        + getStartTime()
        + getStopTime()
        + getTimestampedComments()
    }
}
NavBar ---|> WorkoutHistoryActivity
NavBar ---|> WorkoutActivity
NavBar ---|> SettingsActivity
SessionEntity -[hidden]-- NavBar
SettingsActivity -[hidden]-- DataStorage
WorkoutHistoryActivity -|> WorkoutSessionDetailsActivity
WorkoutActivity ---> ECGDataCollectionService
SendDoctorDataService <- DataStorage
DataStorage ->  ECGDataCollectionService
WorkoutHistoryActivity <---> DataStorage
WorkoutSessionDetailsActivity <--- DataStorage

@enduml
